name: "Setup Test Environment"
description: "Setup the environment for testing in CI"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        uv pip install --system -r requirements.txt
      shell: bash

    - name: Install yq
      run: sudo snap install yq
      shell: bash

    - name: Add test script directory to PATH
      run: echo "$(pwd)/scripts/test" >> $GITHUB_PATH
      shell: bash
