name: Build TAP Schema and Datalink

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          # Need to clone everything for the git tags.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          uv pip install --system -r requirements.txt
          uv pip install --system pytest

      - name: Install sdm_schemas
        run: uv pip install --system --no-deps .

      - name: Run Python tests
        run: pytest

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Run the build
        id: build-tap-schema
        run: ./build-all
        working-directory: ./tap-schema

      - name: Build datalink release
        id: build-datalink
        run: ./build
        working-directory: ./datalink

      - name: Release Datalink
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            datalink/datalink-columns.zip
            datalink/datalink-snippets.zip
