name: Run Database Tests
on:
  push:

jobs:
  call_test_postgresql:
    uses: ./.github/workflows/test_postgresql.yaml

  call_test_mysql:
    uses: ./.github/workflows/test_mysql.yaml

  call_test_sqlite:
    uses: ./.github/workflows/test_sqlite.yaml
