name: Felis schema UX rule check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Only do Docker builds of ticket branches and tagged releases.
    # if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/tickets/')

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        id: depend
        run: pip install -r requirements.txt

      - name: Validate YAML files
        id: validate-yaml
        run: ./validator ../yml/*.yaml
